
name: Build Fedora container

on:
  workflow_dispatch:
jobs:
  build:
    name: build container
    runs-on: ubuntu-24.04
    steps:
      - name: Check out microshift repository
        uses: actions/checkout@v3

      - name: Build Container
        shell: bash
        run: |
          sudo apt-get install podman -y
          podman build  -f okd/src/microshift-okd-builder.Containerfile
