
name: Build Fedora container

on:
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: builder
jobs:
  build:
    name: build container
    runs-on: ubuntu-24.04
    steps:
      - name: Check out microshift repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Buildah Action
        uses: redhat-actions/buildah-build@v2
        with:
          image: my-new-image
          tags: latest
          archs: amd64, arm64
          containerfiles: ./okd/src/microshift-okd-builder.Containerfile
          context:  ./okd/src/
