name: On rebased build RPMs and SRPMs

on:
  workflow_dispatch:
  push:
    branches:
      - 'okd-**'
jobs:
  build:
    name: Make microshift rpms
    runs-on: ubuntu-24.04
    steps:
      - name: Check out microshift repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Install podman
        shell: bash
        run: |
          sudo apt-get install podman -y

      - name: Make x86 rpms
        shell: bash
        run: |
          podman run -v .:/src:Z  ghcr.io/dsedg/builder:latest sh -c "make build; make rpm; make srpm; make clean"

      - name: Make aarch64 rpms
        shell: bash
        run: |
          podman run --arch aarch64 -v .:/src:Z  ghcr.io/dsedg/builder:latest sh -c "make build; make rpm; make srpm; make clean"

      - name: uploads RPMs
        uses: actions/upload-artifact@v4
        with:
          name: RPMs
          path: _output/rpmbuild/RPMS

      - name: uploads SRPMs
        uses: actions/upload-artifact@v4
        with:
          name: SRPMs
          path: _output/rpmbuild/SRPMS
